### ISSUE TITLE
After device registration, ideally, I should get a go/no go on all systems

### ISSUE THREAD

**Issue by semafor** [FriskByBergen/python-friskby-controlpanel#4]
Dashboard should:

- Know that a device has been registered (either use the config, or the db)
- Tell the user what the systemd services are doing?
- Tell the user whether or not everything is a-ok.

What does a-ok imply?

If the DAO returns no rows:
- Open DAO
- Initiate sampling
- Confirm sample in DAO
- Initiate submittal
- Confirm sample uploaded

If DAO returns rows:
- Confirm that something has a) been sampled no longer than SAMPLE_LIMIT ago, b) something has been uploaded no longer than SAMPLE_LIMIT ago.

**Comment by pgdr** [comment]
1. Download a config file (using your own `config_file.post_key`) confirms that we have a valid device ID, a valid `post_key` and that we are connected to the Internet.
2. The existence of the dao-file confirms that the dao has been initialized at least once.
3. It's problematic to verify that the `sds011` works; we could ask it to sample for us, but if it's already sampling, we won't be able to connect to that port. `journalctl -u friskby-sampler`
4. If the DAO contains _uploaded_ rows, that's a good indication that things work, and indeed, if we have an uploaded row that's less than 20 minutes old, we can be confident that we're up and running.

**Comment by semafor** [comment]
Partially solved by pull #5, but seems I will have to wait with the latter part of the status (using DAO) until [1] has been solved. This is because I don't know what the sql path is. Maybe there's a way now, but having a local settings file would help.

[1] https://github.com/FriskByBergen/python-friskby/issues/8
